spring:
  main:
    allow-circular-references: true
  application:
    name: moveList
    locale: ru
  datasource:
    url: jdbc:mysql://localhost:3319/movelist
    username: wladyslow
    password: qPloR1785
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
        ddl-auto: validate
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: movelist
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8190
bot:
  name: primMoveBot
  token: 5425067883:AAF4LFPvOFyuz3CYdPpWVXJmzYn0jQE3Rcs
  chatid: -1001834450370
  recountNewMoves: 600000
  recountNewSchedule: 3600000
  activationKey: randomwd